---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sds-local-volume-scheduler
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-local-volume-scheduler")) | nindent 2 }}
data:
  scheduler-extender-config.yaml: |-
    listen: "localhost:8099"
    default-divisor: 1
{{- if eq .Values.sdsLocalVolume.logLevel "ERROR" }}
    log-level: "0"
{{- else if eq .Values.sdsLocalVolume.logLevel "WARN" }}
    log-level: "1"
{{- else if eq .Values.sdsLocalVolume.logLevel "INFO" }}
    log-level: "2"
{{- else if eq .Values.sdsLocalVolume.logLevel "DEBUG" }}
    log-level: "3"
{{- else if eq .Values.sdsLocalVolume.logLevel "TRACE" }}
    log-level: "4"
{{- end }}
  scheduler-config.yaml: |-
    {{- if semverCompare ">= 1.26" .Values.global.discovery.kubernetesVersion }}
    apiVersion: kubescheduler.config.k8s.io/v1
    {{- else }}
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    {{- end }}
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: sds-local-volume
    extenders:
      - urlPrefix: http://localhost:8099
        filterVerb: filter
        prioritizeVerb: prioritize
        weight: 5
        enableHTTPS: false
        httpTimeout: 300000s
        nodeCacheCapable: false
