{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sds-local-volume
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $ (dict "prometheus" "main")) | nindent 2 }}
spec:
  podMetricsEndpoints:
    - targetPort: 8080
      scheme: http
      path: /metrics
      relabelings:
        - regex: endpoint|namespace|pod|container
          action: labeldrop
        - targetLabel: job
          replacement: sds-local-volume-
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - targetLabel: tier
          replacement: cluster
        - sourceLabels: [__meta_kubernetes_pod_ready]
          regex: "true"
          action: keep
  selector:
    matchLabels:
      app: sds-local-volume-scheduler
  namespaceSelector:
    matchNames:
      - d8-{{ .Chart.Name }}
  {{- end }}