---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "d8-{{ .Chart.Name }}-pod-scheduler-mutation"
webhooks:
  - name: "d8-{{ .Chart.Name }}-pod-scheduler-mutation.storage.deckhouse.io"
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: heritage
          operator: NotIn
          values:
            - deckhouse
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/pod-scheduler-mutation"
      caBundle: |
        {{ .Values.sdsLocalVolume.internal.customWebhookCert.ca }}

    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
