{{- define "kube_scheduler_resources" }}
cpu: 10m
memory: 30Mi
{{- end }}

{{- define "sds_lvm_scheduler_extender_resources" }}
cpu: 10m
memory: 25Mi
{{- end }}

{{- $kubeVersion := semver .Values.global.discovery.kubernetesVersion -}}
{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sds-lvm-scheduler
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-lvm-scheduler")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sds-lvm-scheduler
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: kube-scheduler
      minAllowed:
        {{- include "kube_scheduler_resources" . | nindent 8 }}
      maxAllowed:
        memory: 60Mi
        cpu: 20m
    - containerName: sds-lvm-scheduler-extender
      minAllowed:
        {{- include "sds_lvm_scheduler_extender_resources" . | nindent 8 }}
      maxAllowed:
        memory: 40Mi
        cpu: 20m
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sds-lvm-scheduler
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-lvm-scheduler" )) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: sds-lvm-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-lvm-scheduler
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-lvm-scheduler" )) | nindent 2 }}
spec:
  {{- include "helm_lib_deployment_strategy_and_replicas_for_ha" . | nindent 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sds-lvm-scheduler
  template:
    metadata:
      labels:
        app: sds-lvm-scheduler
    spec:
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "sds-lvm-scheduler")) | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      containers:
        - name: kube-scheduler
          {{- include "helm_lib_module_container_security_context_read_only_root_filesystem_capabilities_drop_all" . | nindent 10 }}
          command:
          - kube-scheduler
          {{- if semverCompare ">= 1.22" .Values.global.discovery.kubernetesVersion }}
          - --config=/etc/kubernetes/scheduler-config.yaml
          {{- else }}
          - --scheduler-name=sds-lvm
          - --policy-configmap=sds-lvm-scheduler
          - --policy-configmap-namespace=d8-{{ .Chart.Name }}
          {{- end }}
          - --leader-elect=true
          - --leader-elect-resource-name=sds-lvm-scheduler
          - --leader-elect-resource-namespace=$(NAMESPACE)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- /* Here we use kube-scheduler image from control-plane-manager module */}}
          image: {{ include "helm_lib_module_image" (list (dict "Chart" (dict "Name" "control-plane-manager") "Values" .Values) (list "kubeScheduler" $kubeVersion.Major $kubeVersion.Minor | join "")) }}
          imagePullPolicy: IfNotPresent
          startupProbe:
            failureThreshold: 24
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          {{- if semverCompare ">= 1.22" .Values.global.discovery.kubernetesVersion }}
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: scheduler-config
          {{- end }}
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
              {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "kube_scheduler_resources" . | nindent 14 }}
              {{- end }}
        - name: sds-lvm-scheduler-extender
          {{- include "helm_lib_module_container_security_context_read_only_root_filesystem_capabilities_drop_all" . | nindent 10 }}
          image: {{ include "helm_lib_module_image" (list . "sdsLvmSchedulerExtender") }}
          imagePullPolicy: IfNotPresent
          args:
            - sds-lvm-scheduler-extender
            - --config=/etc/sds-lvm-scheduler-extender/scheduler-extender-config.yaml
          volumeMounts:
          - mountPath: /etc/sds-lvm-scheduler-extender
            name: scheduler-config
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
              {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "sds_lvm_scheduler_extender_resources" . | nindent 14 }}
              {{- end }}
      {{- if semverCompare ">= 1.22" .Values.global.discovery.kubernetesVersion }}
      volumes:
      - configMap:
          defaultMode: 420
          name: sds-lvm-scheduler
        name: scheduler-config
      {{- end }}
      serviceAccountName: sds-lvm-scheduler
