x-config-version: 2
type: object
required: []
properties:
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module log level.
    default: INFO
